// Exports the compiled MemoryRegistry ABI into packages/sdk/src/abi.ts (run after `forge build`).
import { readFileSync, writeFileSync } from "node:fs";
const root = new URL("../", import.meta.url);
const { abi } = JSON.parse(readFileSync(new URL("chain/out/MemoryRegistry.sol/MemoryRegistry.json", root), "utf8"));
const identity = [
  { type: "function", name: "ownerOf", stateMutability: "view", inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "tokenURI", stateMutability: "view", inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ name: "", type: "string" }] },
];
writeFileSync(
  new URL("packages/sdk/src/abi.ts", root),
  "// Generated by scripts/export-abi.mjs from chain/out (forge build). Do not edit.\n" +
    `export const memoryRegistryAbi = ${JSON.stringify(abi, null, 2)} as const;\n\n` +
    `/** The subset of the ERC-8004 IdentityRegistry (ERC-721) the SDK reads. */\n` +
    `export const identityRegistryAbi = ${JSON.stringify(identity, null, 2)} as const;\n`,
);
console.log("wrote packages/sdk/src/abi.ts", abi.length, "entries");
