// Registers the two demo agents (Sage = assistant, Wayfarer = planner) as ERC-8004 identities on Monad testnet,
// publishes their X25519 keys + operators to the MemoryRegistry, funds the operators, and writes the gitignored
// env files apps/agent/.env.assistant and .env.planner. Idempotent: existing env files are reused.
//
//   npx tsx scripts/register-agents.ts
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { x25519 } from "@noble/curves/ed25519.js";
import { createPublicClient, createWalletClient, decodeEventLog, http, parseAbi, parseEther, toHex, type Hex } from "viem";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { monadTestnet } from "viem/chains";
import { EngramAgent, deployments } from "@engram/sdk";

const env = Object.fromEntries(
  readFileSync("chain/.env", "utf8").split("\n").filter((l) => /^[A-Z0-9_]+=/.test(l)).map((l) => [l.slice(0, l.indexOf("=")), l.slice(l.indexOf("=") + 1).trim()]),
);
const d = deployments.monadTestnet;
const transport = http(d.rpcUrl);
const pub = createPublicClient({ chain: monadTestnet, transport });
const holder = createWalletClient({ chain: monadTestnet, transport, account: privateKeyToAccount(env.DEPLOYER_PRIVATE_KEY as Hex) });
const identityAbi = parseAbi(["function register(string agentURI) returns (uint256)", "event Registered(uint256 indexed agentId, string agentURI, address indexed owner)"]);
const log = (op: string, f: Record<string, unknown>) => console.log(JSON.stringify({ stage: "register-agents", op, ...f }));

const personas = [
  { id: "assistant", port: 3201 },
  { id: "planner", port: 3202 },
] as const;

function readEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  return Object.fromEntries(readFileSync(path, "utf8").split("\n").filter((l) => /^[A-Z0-9_]+=/.test(l)).map((l) => [l.slice(0, l.indexOf("=")), l.slice(l.indexOf("=") + 1).split("#")[0]!.trim()]));
}

for (const p of personas) {
  const file = `apps/agent/.env.${p.id}`;
  const prev = readEnvFile(file);
  const origin = `http://localhost:${p.port}`;
  let agentId = prev.AGENT_ID && prev.AGENT_ID !== "0" ? BigInt(prev.AGENT_ID) : undefined;
  const xPriv = prev.AGENT_X25519_PRIVATE_KEY ? new Uint8Array(Buffer.from(prev.AGENT_X25519_PRIVATE_KEY.slice(2), "hex")) : x25519.utils.randomSecretKey();
  const opKey = (prev.AGENT_OPERATOR_KEY as Hex | undefined) ?? generatePrivateKey();
  const operator = privateKeyToAccount(opKey);

  if (agentId === undefined) {
    // tokenURI points at the app's own card; switch to the https URL with setAgentURI once deployed.
    const hash = await holder.writeContract({ address: d.identityRegistry, abi: identityAbi, functionName: "register", args: [`${origin}/agent-card.json`] });
    const r = await pub.waitForTransactionReceipt({ hash });
    for (const l of r.logs) {
      try {
        const ev = decodeEventLog({ abi: identityAbi, data: l.data, topics: l.topics });
        if (ev.eventName === "Registered") agentId = ev.args.agentId;
      } catch {
        /* other log */
      }
    }
    if (agentId === undefined) throw new Error("no Registered event");
    log("registered", { persona: p.id, agentId: agentId.toString(), tx: hash });
  }

  const [curPub, curOp] = (await pub.readContract({
    address: d.registry, abi: parseAbi(["function agentKeysOf(uint256) view returns (bytes32, address)"]), functionName: "agentKeysOf", args: [agentId],
  })) as [Hex, Hex];
  const wantPub = toHex(x25519.getPublicKey(xPriv));
  if (curPub.toLowerCase() !== wantPub.toLowerCase() || curOp.toLowerCase() !== operator.address.toLowerCase()) {
    const tx = await EngramAgent.publishKeys({ config: d, agentId, x25519PublicKey: x25519.getPublicKey(xPriv), operator: operator.address, holder });
    log("keys-published", { persona: p.id, agentId: agentId.toString(), tx });
  }

  if ((await pub.getBalance({ address: operator.address })) < parseEther("0.1")) {
    const tx = await holder.sendTransaction({ to: operator.address, value: parseEther("0.3") });
    await pub.waitForTransactionReceipt({ hash: tx });
    log("operator-funded", { persona: p.id, operator: operator.address, tx });
  }

  const lines = [
    `# Generated by scripts/register-agents.ts (gitignored). Testnet only.`,
    `AGENT_PERSONA=${p.id}`,
    `NEXT_DIST_DIR=.next-${p.id}`,
    `APP_ORIGIN=${origin}`,
    `AGENT_ID=${agentId}`,
    `AGENT_X25519_PRIVATE_KEY=${toHex(xPriv)}`,
    `AGENT_OPERATOR_KEY=${opKey}`,
    `INDEXER_URL=${prev.INDEXER_URL ?? "http://localhost:8090/v1/graphql"}`,
    `KIMI_BASE_URL=${prev.KIMI_BASE_URL ?? "https://api.moonshot.ai/v1"}`,
    `KIMI_API_KEY=${prev.KIMI_API_KEY ?? ""}`,
    `KIMI_MODEL=${prev.KIMI_MODEL ?? "kimi-k2.6"}`,
    `NEXT_PUBLIC_VAULT_URL=${prev.NEXT_PUBLIC_VAULT_URL ?? "http://localhost:3100"}`,
    `NEXT_PUBLIC_AGENT_ID=${agentId}`,
    `NEXT_PUBLIC_AGENT_PERSONA=${p.id}`,
  ];
  writeFileSync(file, lines.join("\n") + "\n", { mode: 0o600 });
  log("env-written", { persona: p.id, agentId: agentId.toString(), file, operator: operator.address, kimiKeySet: !!prev.KIMI_API_KEY });
}
